### ISSUE TITLE
How to set region in code with the API

### ISSUE THREAD

**Issue by toimuonthunghiem** [SergeyDertan/SRegionProtector#18]
Is there any way to set the region for the player with code?

**Comment by toimuonthunghiem** [comment]
Also, something wrong with the maven dependency.

`Some problems were encountered while building the effective model for me.thanh:myplugin:jar:1.0-SNAPSHOT
'dependencies.dependency.version' for sergeydertan.sregionprotector:SRegionProtector:jar is either LATEST or RELEASE (both of them are being deprecated) @ line 44, column 22
It is highly recommended to fix these problems because they threaten the stability of your build.
For this reason, future Maven versions might no longer support building such malformed projects.
`

**Comment by SergeyDertan** [comment]
Fixed

**Comment by SergeyDertan** [comment]
````
RegionManager regionManager = SRegionProtectorMain.getInstance().getRegionManager();
regionManager.createRegion("name","owner name, no matter",pos1,pos2,level);
````
