### ISSUE TITLE
Fix the plugin

### ISSUE THREAD

**Issue by Saxavlax001** [SergeyDertan/SRegionProtector#2]
Dude,you made a good plugin,but saved regions and all config files aren't exist  in SRegionProtector folder and folder doesn't exist.Fix it or else plugin doesn't do nothing,so it's useless.

**Comment by SergeyDertan** [comment]
Where are u searching SRP folder? I should be located at {SERVER_MAIN_FOLDER}/Sergey_Dertan_Plugins/

**Comment by Saxavlax001** [comment]
In my plugins folder I was searching

**Comment by Saxavlax001** [comment]
And I don't have that folder you said,I searched now

**Comment by SergeyDertan** [comment]
Do u have any errors? Send me u`r server main folder screenshot

**Comment by Saxavlax001** [comment]
![img_20181223_182414](https://user-images.githubusercontent.com/22281205/50385545-0d793900-06e0-11e9-8fa9-fd599b234237.jpg)

**Comment by Saxavlax001** [comment]
The main folder is my ip of server I think,so that is the main folder I think.

**Comment by SergeyDertan** [comment]
Any errors?

**Comment by Saxavlax001** [comment]
wait

**Comment by Saxavlax001** [comment]
Weird,now the folder you said appeared idk how.

**Comment by Saxavlax001** [comment]
Maybe the ftp weren't reloaded so I'll close the issue.
