### ISSUE TITLE
/wand

### ISSUE THREAD

**Issue by snaildos** [SergeyDertan/SRegionProtector#21]
/wand interfears with the FAWE //wand.
Can you change it to /region wand or smthing?

Thanks.

**Comment by SergeyDertan** [comment]
You already can use /rg wand

**Comment by snaildos** [comment]
No. Because when I do /wand for FAWE, SREGION Interfears.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by SergeyDertan** [comment]
Looks like outlook don`t work in my country

**Comment by SergeyDertan** [comment]
oh, u mean u can`t use wand command from fawe?

**Comment by snaildos** [comment]
Yes

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by snaildos** [comment]
So I cannot use fawe because the plugin is interfering with it. So maybe remove /wand and just have it as /rg wand

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by SergeyDertan** [comment]
https://github.com/SergeyDertan/SRegionProtector/commit/e694286a8862a8e821dec7b4b0bad989871baf88

**Comment by snaildos** [comment]
Where's the jar file?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by SergeyDertan** [comment]
I`ll upload to the nukkit site

**Comment by SergeyDertan** [comment]
Done, wait for approve

**Comment by snaildos** [comment]
Thank you.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
