### ISSUE TITLE
it crashed when auto save 

### ISSUE THREAD

**Issue by Zaohon** [SergeyDertan/SRegionProtector#23]
Error log below
https://paste.ubuntu.com/p/3Xzw8vNZB7/

**Comment by SergeyDertan** [comment]
Is it whole log?

**Comment by SergeyDertan** [comment]
send me plugin`s data folder

**Comment by Zaohon** [comment]
https://paste.ubuntu.com/p/k9cKx6gCJX/

It s the full log and i swear i didnt edit any config

**Comment by SergeyDertan** [comment]
are u sure its caused by region protector?

**Comment by Zaohon** [comment]
when i first saw the error , i did think it is a nukkit issue .
Then i reported it to nukkit but they told me check the SRegionProtector
Also i found the error will appear randomly after automatically save successfully
It is so weird that i cant figure if it is a region protector bug
i run in the newest nukkit.

**Comment by Zaohon** [comment]
https://paste.ubuntu.com/p/QtKWyrZ6dZ/

**Comment by SergeyDertan** [comment]
U have no regions on the server?

**Comment by SergeyDertan** [comment]
hm. I`ll check it

**Comment by SergeyDertan** [comment]
u can disable auto save in the config

**Comment by SergeyDertan** [comment]
Can`t reproduce
