### ISSUE TITLE
Flags don't work as intended 

### ISSUE THREAD

**Issue by Dazzer135** [SergeyDertan/SRegionProtector#24]
Hey, when I put a flag as break =
State: false people can break stuff
But when I do 
Pvp
State:true
People can't pvp
So I was wondering is false = true and true = false?

**Comment by SergeyDertan** [comment]
True means that flag is enabled, so if PvP flag enabled it prevents PvP, and when break flag state is false, it means that break flag disabled and anyone can break blocks

**Comment by Dazzer135** [comment]
Ok thanks
