### ISSUE TITLE
EventPriority set too high

### ISSUE THREAD

**Issue by NoahBPeterson** [SergeyDertan/SRegionProtector#26]
https://github.com/SergeyDertan/SRegionProtector/blob/master/src/main/java/Sergey_Dertan/SRegionProtector/Event/RegionEventsHandler.java

EventPriority in NukkitX executes "lower" priority events before "higher" priority events. I ran into an issue with my plugin where BlockBreakEvent's eventhandler was set to the same level as yours, but mine ran first. This gives the player the block they broke. But if they're in a region protected by your plugin where they can't break blocks, the block event is canceled, yet the player keeps the block.

I have since updated my plugin to increase the event priority due to this not being the first duplication bug of this sort. However, having your event priority set to run after most other plugins (EventPriority.HIGH) could cause more issues with other plugins. Is it not better to have your handlers run sooner (EventPriority.LOWEST) so that if they need to cancel other events, no plugin that uses the same event handlers can continue executing?

**Comment by SergeyDertan** [comment]
https://github.com/SergeyDertan/SRegionProtector/commit/9858b1f065a1c2a888512ef13a8b60b980070e14
