### ISSUE TITLE
Dosnt work now!

### ISSUE THREAD

**Issue by snaildos** [SergeyDertan/SRegionProtector#27]
After the problem with fawe, I updated it and when i have fawe installed it wont work AT ALL!
Please fix!!!
Or change the wand command to /regionwand

**Comment by SergeyDertan** [comment]
U cant get wand?

**Comment by snaildos** [comment]
I can't do anything.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by SergeyDertan** [comment]
Whole plugin isnt working? Explain pls

**Comment by snaildos** [comment]
The whole plugin dosn't work with FAWE

**Comment by SergeyDertan** [comment]
Any errors? During loading?

**Comment by snaildos** [comment]
No

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by snaildos** [comment]
It's weird I think it'd the proxy. Does this support proxy support?

**Comment by SergeyDertan** [comment]
Idk, never used proxy

**Comment by SergeyDertan** [comment]
No proxy support
