### ISSUE TITLE
Suggestion: About Making Region

### ISSUE THREAD

**Issue by GoodLucky777** [SergeyDertan/SRegionProtector#28]
I know that the Region plugin restricts region creation by permission. But how about using EconomyAPI, for example, setting 1$ per block region in config.yml and enabling the region creation if you have enough money? For example, plugin check if you have enough money before it's created, and then make as much money as there are region blocks when it's created. And if you have a lot of money, you can use permissions to restrict the creation of unlimited regions. This will be the best plugin of the NukkitX block protection plugin!

**Comment by SergeyDertan** [comment]
Good idea, I`ll make it when I have time

**Comment by GoodLucky777** [comment]
thank you!

**Comment by SergeyDertan** [comment]
https://github.com/SergeyDertan/SRegionProtector/commit/5395d699399afd7d3a6ad8a9ade09f2b36477ce0
