### ISSUE TITLE
Multiworld regions

### ISSUE THREAD

**Issue by Saxavlax001** [SergeyDertan/SRegionProtector#3]
Plugin doesn't load regions from other worlds if worlds aren't loaded,and regions from the other worlds are enabled when I do reload only and when players are in two different worlds for example,but that its temporary solution.Do sth to fix it pls.

**Comment by Poustmal** [comment]
@SergeyDertan

**Comment by Saxavlax001** [comment]
Can you do sth for that pls?

**Comment by SergeyDertan** [comment]
Fixed, u can use google drive link or compile by u`r self

**Comment by Saxavlax001** [comment]
It says region not found again in another worlds but I have already set a region.

**Comment by Saxavlax001** [comment]
Now even in the main world set in server.properties it says "Region not found".So protect is not working.

**Comment by Poustmal** [comment]
But it says loaded 2 regions.
