### ISSUE TITLE
What does it mean?

### ISSUE THREAD

**Issue by GoodLucky777** [SergeyDertan/SRegionProtector#31]
https://github.com/SergeyDertan/SRegionProtector/blob/5395d699399afd7d3a6ad8a9ade09f2b36477ce0/src/main/resources/lang/eng.yml#L8

Can't copy resource resource

**Comment by GoodLucky777** [comment]
I think is should be like
Can't copy resource, resource: {@err}, disabling plugin...
or
Can't copy resource {@err}, disabling plugin...

**Comment by SergeyDertan** [comment]
https://github.com/SergeyDertan/SRegionProtector/commit/dcb65cdcd27b496bcf91936f955d9f8cb79e1312
