### ISSUE TITLE
What is different?

### ISSUE THREAD

**Issue by GoodLucky777** [SergeyDertan/SRegionProtector#32]
https://github.com/SergeyDertan/SRegionProtector/blob/5395d699399afd7d3a6ad8a9ade09f2b36477ce0/src/main/resources/lang/eng.yml#L34
https://github.com/SergeyDertan/SRegionProtector/blob/5395d699399afd7d3a6ad8a9ade09f2b36477ce0/src/main/resources/lang/eng.yml#L35

What is different?

**Comment by SergeyDertan** [comment]
the second is for receiving messages when the first is for sending
https://github.com/SergeyDertan/SRegionProtector/commit/e61f156e64724536b13df08ebedb9576b525b22e
