### ISSUE TITLE
Wrong words

### ISSUE THREAD

**Issue by GoodLucky777** [SergeyDertan/SRegionProtector#33]
https://github.com/SergeyDertan/SRegionProtector/blob/5395d699399afd7d3a6ad8a9ade09f2b36477ce0/src/main/resources/lang/eng.yml#L64
https://github.com/SergeyDertan/SRegionProtector/blob/5395d699399afd7d3a6ad8a9ade09f2b36477ce0/src/main/resources/lang/eng.yml#L66

It is second pos, but it says it is first pos.

**Comment by SergeyDertan** [comment]
https://github.com/SergeyDertan/SRegionProtector/commit/d83f9f78884bef5e078735824fd2d8e071bf6fd8
