### ISSUE TITLE
You dont permission

### ISSUE THREAD

**Issue by GoodLucky777** [SergeyDertan/SRegionProtector#34]
https://github.com/SergeyDertan/SRegionProtector/blob/5395d699399afd7d3a6ad8a9ade09f2b36477ce0/src/main/resources/lang/eng.yml#L176

I think it is wrong.

**Comment by SergeyDertan** [comment]
https://github.com/SergeyDertan/SRegionProtector/commit/942c469c8a94ef90603d6d6d6ceff8cdfe4a6306
