### ISSUE TITLE
wrong word

### ISSUE THREAD

**Issue by GoodLucky777** [SergeyDertan/SRegionProtector#36]
https://github.com/SergeyDertan/SRegionProtector/blob/5395d699399afd7d3a6ad8a9ade09f2b36477ce0/src/main/resources/lang/eng.yml#L187

It need to be owner, but it says member.

**Comment by SergeyDertan** [comment]
https://github.com/SergeyDertan/SRegionProtector/commit/104b384961deab93c4d3ede264784abf213a4146
