### ISSUE TITLE
Level or World

### ISSUE THREAD

**Issue by GoodLucky777** [SergeyDertan/SRegionProtector#38]
https://github.com/SergeyDertan/SRegionProtector/blob/5395d699399afd7d3a6ad8a9ade09f2b36477ce0/src/main/resources/lang/eng.yml#L284

I think people will confuse because rg info says "world" but this says "level". Can you make these to same word?

**Comment by SergeyDertan** [comment]
https://github.com/SergeyDertan/SRegionProtector/commit/9d34f654a8c5af5c96fbc9061a9c8edb019ef9a0
