### ISSUE TITLE
Explosion Bug

### ISSUE THREAD

**Issue by GoodLucky777** [SergeyDertan/SRegionProtector#43]
When I explode something next to Region, it will also explode Region too.

**Comment by SergeyDertan** [comment]
Have u enabled ExplodeBlockBreak flag?

**Comment by GoodLucky777** [comment]
Yes it was denied, it happen when I make massive explode

**Comment by SergeyDertan** [comment]
it need to be enabled in the config and in the region

**Comment by SergeyDertan** [comment]
what do u mean by massive?

**Comment by GoodLucky777** [comment]
explode and explode block is denied but when I make a explode with plugin with power 100 two times, it will blow up Regions too.

**Comment by GoodLucky777** [comment]
it is very weird

**Comment by SergeyDertan** [comment]
what plugin?

**Comment by GoodLucky777** [comment]
```
Location explodePos = block.getLocation();
Explosion explosion = new Explosion(explodePos, 100.0, null);
explosion.explodeA();
explosion.explodeB();
```

**Comment by SergeyDertan** [comment]
check https://github.com/SergeyDertan/SRegionProtector/commit/1eb39312afe065485fd2ed61a3d17af58b2bf1cb

**Comment by SergeyDertan** [comment]
Checked ?

**Comment by GoodLucky777** [comment]
I think not.
![20200622_164525](https://user-images.githubusercontent.com/43497313/85261890-ddaf1b00-b4a7-11ea-986b-2ef06e4d10f0.jpg)

**Comment by SergeyDertan** [comment]
That result of explode?
Cant understood if it working

**Comment by GoodLucky777** [comment]
It is weird that sometimes it prevent it but sometimes it exploded.

**Comment by SergeyDertan** [comment]
If exploding caused not by entity there is no way to prevent that
Only EntityExplodeEvent called when entity explodes
https://github.com/NukkitX/Nukkit/blob/master/src/main/java/cn/nukkit/level/Explosion.java#L127

**Comment by SergeyDertan** [comment]
When there is no ExplodeEvent without entity u need to add fake entity to the explosion
