### ISSUE TITLE
Не работает

### ISSUE THREAD

**Issue by feanchy** [SergeyDertan/SRegionProtector#46]
Плагин не работает, может к нему прилагается дополнительный плагин?

**Comment by SergeyDertan** [comment]
в консоли какие-то ошибки?

**Comment by feanchy** [comment]
> в консоли какие-то ошибки?

Нет, просто не работает, когда пишу plugins плагин красного цвета

**Comment by Lusmft** [comment]
Не включается плагин, в консоли выходят ошибки после загрузки библиотек.

**Comment by feanchy** [comment]
Что в консоли когда сервер запускается с плагином:
22:03:55 [INFO ] [SRegionProtector] Инициализация SRegionProtector V_19.9 от Sergey Dertan...
22:03:55 [INFO ] [SRegionProtector] Загрузка библиотек...
22:03:55 [ERROR] Throwing
java.lang.RuntimeException: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:443) ~[nukkit-1.0-SNAPSHOT.jar:?]

**Comment by SergeyDertan** [comment]
в наките баг связанный с загрузкой библиотек в джаве 8+

с 8 джавой всё нормально будет

https://github.com/NukkitX/Nukkit/issues/912
