### ISSUE TITLE
Many Bug with Nemisys

### ISSUE THREAD

**Issue by GoodLucky777** [SergeyDertan/SRegionProtector#49]
Can you support Nemisys too? It makes too many error and bug.

**Comment by SergeyDertan** [comment]
Never used it
What bugs exactly?

**Comment by GoodLucky777** [comment]
Command is working but no output messages

**Comment by SergeyDertan** [comment]
https://github.com/SergeyDertan/SRegionProtector/commit/feecbc11c428d08a14d496f70cc5c93584edb09b
