### ISSUE TITLE
Can you add Hopper Flag?

### ISSUE THREAD

**Issue by GoodLucky777** [SergeyDertan/SRegionProtector#51]
Can you add Hopper Flag? It will be useful.

**Comment by feanchy** [comment]
> Can you add Hopper Flag? It will be useful.

what does this flag do?

**Comment by SergeyDertan** [comment]
> > Can you add Hopper Flag? It will be useful.
> 
> what does this flag do?

Yes

**Comment by GoodLucky777** [comment]
> > Can you add Hopper Flag? It will be useful.
> 
> what does this flag do?

Block hopper move items and also hopper minecart too

**Comment by SergeyDertan** [comment]
https://github.com/SergeyDertan/SRegionProtector/commit/cb5407b10f17e9b003fbac6595f190f7db1c22ee
