### ISSUE TITLE
Vk

### ISSUE THREAD

**Issue by feanchy** [SergeyDertan/SRegionProtector#52]
У вас есть ВК?

**Comment by SergeyDertan** [comment]
есть но захожу редко
есть телеграм

**Comment by feanchy** [comment]
Давай, ВК все равно 0_о

вт, 16 июн. 2020 г., 15:18 SergeyDertan <notifications@github.com>:

**Comment by SergeyDertan** [comment]
https://vk.com/sergey.baharev
