### ISSUE TITLE
Question: What is best multithreaded-loading-threads configuration?

### ISSUE THREAD

**Issue by GoodLucky777** [SergeyDertan/SRegionProtector#54]
In my server there is above 500 regions. How many thread is needed? Is there like example and manual things for this?

**Comment by SergeyDertan** [comment]
Try using 1 thread and check how fast plugin loading

**Comment by GoodLucky777** [comment]
Is this cause lot if CPU usage?

**Comment by SergeyDertan** [comment]
only when loading regions if you have lot of them
I think 1-2 threads is enough for 500 regions

**Comment by GoodLucky777** [comment]
How about `async-commands-threads`? 2 is enough?

**Comment by SergeyDertan** [comment]
Yes, actually u can disable this async functions if you have not lot regions

**Comment by GoodLucky777** [comment]
What is best data provider for this plugin? YAML or MySQL?

**Comment by SergeyDertan** [comment]
no matter, if u want to interact with regions outside the plugin u can choose most suitable provider

**Comment by SergeyDertan** [comment]
I think the question is answered
