### ISSUE TITLE
Size/quantity permissions

### ISSUE THREAD

**Issue by feanchy** [SergeyDertan/SRegionProtector#59]
Добавь новый конфиг где можно настроить количество и размер регионов
Например:
Игрок:
Размер: 150000
Количество регионов которые он может создать: 2
Вип: 
Админ:
Министр:
И т.д

**Comment by SergeyDertan** [comment]
это всё можно сделать с помощью плагина для редактирования прав, да и удобнее так будет.
Добавь разрешения нужным группам
sregionprotector.region.amount.КОЛИЧЕСТВО_МАКС
sregionprotector.region.size.РАЗМЕР_МАКС
