### ISSUE TITLE
Issue 

### ISSUE THREAD

**Issue by Trxgically** [SergeyDertan/SRegionProtector#7]
java version "1.8.0_192"
Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.192-b12, mixed mode)
:/home/container$ java -Xms128M -Xmx4000M -jar nukkit.jar
Using log level 'INFO'
]0;Starting Nukkit Server For Minecraft: PE> 01:44:13 [INFO] Loading nukkit.yml...
> 01:44:14 [INFO] Loading server properties...
> 01:44:14 [INFO] Selected English (eng) as the base language
> 01:44:14 [INFO] Starting Minecraft: PE server version v1.8.0
> 01:44:14 [INFO] Selected Zlib Provider: 2 (cn.nukkit.utils.ZlibThreadLocal)
> 01:44:14 [INFO] Opening server on 0.0.0.0:30120
> 01:44:14 [INFO] This server is running Nukkit version git-a694cf7 "" (API 1.0.7)
> 01:44:14 [INFO] Nukkit is distributed under the LGPL License
> 01:44:18 [INFO] Loading recipes...
> 01:44:19 [INFO] Loaded 954 recipes.
> 01:44:19 [INFO] Successfully loaded 0 resource packs
> 01:44:20 [INFO] Loading DbLib v0.2.5
> 01:44:20 [INFO] [DbLib] Establishing a connection withjdbc:sqlite:nukkit.db (user:nukkit)
> Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
01:44:21 [INFO] [DbLib] DbLib 0.2.5 created by fromgate for nukkit.ru
> 01:44:21 [INFO] Loading EconomyAPI v1.0.1
> 01:44:21 [INFO] Epoll is available. EpollEventLoop will be used.
> 01:44:21 [INFO] Loading WorldEssentials v2.0.3
> 01:44:21 [INFO] Loading RollBossBar v1.1.0
> 01:44:21 [INFO] Loading SimpleCrates v0.9.8
> 01:44:21 [INFO] [SimpleCrates] Loading crates...
> 01:44:21 [INFO] Loading MobPlugin v1.5.9
> 01:44:21 [INFO] Loading AdvancedWelcome v1.1
> 01:44:21 [INFO] Loading SimpleScoreboards v2.2
> 01:44:21 [INFO] Loading SRegionProtector v15.1
> 01:44:21 [INFO] Loading AutoLagClear v1
> 01:44:21 [INFO] Loading EssentialsNK v1.5.0
> 01:44:21 [INFO] Loading AutoSpawn v1.0
> 01:44:21 [INFO] Loading ASkyBlock v0.4.8-ALPHA
> 01:44:22 [INFO] ASkyBlock build-number: a694cf7
> 01:44:22 [INFO] ASkyBlock commit-number: a694cf7b0fe6dcfa3a9dd08801bccd76b83e3316
> 01:44:22 [INFO] [ASkyBlock] Successfully checked config.yml
> 01:44:22 [INFO] Loading Multipass v1.1.2
> 01:44:22 [INFO] Loading MultiChat v1.0.2
> 01:44:22 [INFO] Loading AutoInventory v1.0.2
> 01:44:22 [INFO] [AutoInventory] AutoInventory has been loaded!
> 01:44:22 [INFO] Enabling MobPlugin v1.5.9
> 01:44:23 [INFO] Preparing level "SkyBlockSpawn"
> 01:44:23 [INFO] Preparing level "nether"
> 01:44:23 [INFO] Enabling DbLib v0.2.5
> 01:44:23 [INFO] Enabling EconomyAPI v1.0.1
> 01:44:24 [NOTICE] [EconomyAPI] Data provider was set to: Yaml
> 01:44:24 [INFO] Enabling WorldEssentials v2.0.3
> 01:44:24 [INFO] Enabling RollBossBar v1.1.0
> 01:44:24 [INFO] Enabling SimpleCrates v0.9.8
> 01:44:24 [INFO] SimpleCrates is up to date, with configuration version 0.9.8!
> 01:44:24 [ALERT] java.lang.RuntimeException: java.lang.ClassCastException: java.util.HashMap cannot be cast to cn.nukkit.utils.ConfigSection
at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:439)
at cn.nukkit.Server.enablePlugin(Server.java:676)
at cn.nukkit.Server.enablePlugins(Server.java:665)
at cn.nukkit.Server.<init>(Server.java:507)
at cn.nukkit.Nukkit.main(Nukkit.java:109)
Caused by: java.lang.ClassCastException: java.util.HashMap cannot be cast to cn.nukkit.utils.ConfigSection
at cn.nukkit.utils.ConfigSection.getSection(ConfigSection.java:144)
at cn.nukkit.utils.Config.getSection(Config.java:270)
at ceremonious.crates.Main.loadCrates(Main.java:153)
at ceremonious.crates.Main.onEnable(Main.java:105)
at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89)
at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117)
at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:435)
... 4 more
> 01:44:24 [INFO] Disabling SimpleCrates v0.9.8
> 01:44:24 [INFO] [SimpleCrates] Plugin disabled!
> 01:44:24 [INFO] Enabling AdvancedWelcome v1.1
> 01:44:24 [INFO] [AdvancedWelcome] WelcomeUI By SIVANNKH has been enabled!
> 01:44:24 [INFO] Enabling SimpleScoreboards v2.2
> 01:44:24 [INFO] [SimpleScoreboards] Downloading ScoreboardAPI...
> 01:44:28 [INFO] [SimpleScoreboards] ScoreboardAPI downloaded successfully
> 01:44:28 [INFO] Loading ScoreboardPlugin v1.0
> 01:44:28 [INFO] [SimpleScoreboards] Downloading PlaceholderAPI...
> 01:44:28 [INFO] [SimpleScoreboards] PlaceholderAPI downloaded successfully
> 01:44:28 [INFO] Loading PlaceholderAPI v1.2
> 01:44:29 [INFO] [PlaceholderAPI] Downloading KotlinLib...
> 01:44:30 [INFO] [PlaceholderAPI] KotlinLib successfully downloaded
> 01:44:30 [INFO] Loading KotlinLib v1.0
> 01:44:30 [INFO] Enabling SRegionProtector v15.1
> 01:44:31 [INFO] [SRegionProtector] Initializing SRegionProtector V_15.1 by Sergey Dertan...
> 01:44:31 [INFO] [SRegionProtector] Settings initializing...
> 01:44:31 [INFO] [SRegionProtector] Data provider initializing...
> 01:44:31 [INFO] [SRegionProtector] Data provider was set to YAML
> 01:44:31 [INFO] [SRegionProtector] Regions initializing...
> 01:44:31 [INFO] [SRegionProtector] Loaded 0 regions.
> 01:44:31 [INFO] [SRegionProtector] Chunks initializing...
> 01:44:31 [INFO] [SRegionProtector] Loaded 0 chunks.
> 01:44:31 [INFO] [SRegionProtector] Events handlers initializing...
> 01:44:31 [ALERT] java.lang.RuntimeException: java.lang.NoClassDefFoundError: cn/nukkit/event/block/LiquidFlowEvent
at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:439)
at cn.nukkit.Server.enablePlugin(Server.java:676)
at cn.nukkit.Server.enablePlugins(Server.java:665)
at cn.nukkit.Server.<init>(Server.java:507)
at cn.nukkit.Nukkit.main(Nukkit.java:109)
Caused by: java.lang.NoClassDefFoundError: cn/nukkit/event/block/LiquidFlowEvent
at Sergey_Dertan.SRegionProtector.Main.SRegionProtectorMain.initEventsHandlers(SRegionProtectorMain.java:200)
at Sergey_Dertan.SRegionProtector.Main.SRegionProtectorMain.onEnable(SRegionProtectorMain.java:84)
at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89)
at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117)
at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:435)
... 4 more
Caused by: java.lang.ClassNotFoundException: cn.nukkit.event.block.LiquidFlowEvent
at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:34)
at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:28)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 9 more
> 01:44:31 [INFO] Disabling SRegionProtector v15.1
> 01:44:31 [INFO] [SRegionProtector] Disabling SRegionProtector V_15.1 by Sergey Dertan...
> 01:44:31 [INFO] [SRegionProtector] Starting saving...
> 01:44:31 [INFO] [SRegionProtector] Removed 0 empty chunks.
> 01:44:31 [INFO] [SRegionProtector] Saved 0 chunks.
> 01:44:31 [INFO] [SRegionProtector] Saved 0 regions
> 01:44:31 [INFO] [SRegionProtector] SRegionProtector disabled.
> 01:44:31 [INFO] Enabling AutoLagClear v1
> 01:44:31 [INFO] [AutoLagClear] AutoLagClear - [Enabled]
> 01:44:31 [INFO] Enabling EssentialsNK v1.5.0
> 01:44:31 [INFO] [EssentialsNK] EssentialsNK Loaded!
> 01:44:31 [INFO] Enabling AutoSpawn v1.0
> 01:44:31 [INFO] [AutoSpawn] has been enabled.
> 01:44:31 [INFO] Enabling ASkyBlock v0.4.8-ALPHA
> 01:44:32 [INFO] Preparing level "SkyBlock"
> 01:44:32 [INFO] [ASkyBlock] Enabling ASkyBlock - Founders Edition (API 24)
> 01:44:32 [INFO] [ASkyBlock] Loading offline messages...
> 01:44:32 [INFO] [ASkyBlock] Loading the Island Framework
> 01:44:32 [INFO] [ASkyBlock] Starting Schematic Resource Pack.
> 01:44:33 [INFO] [ASkyBlock] Successfully loaded 4 Schematic
> 01:44:33 [INFO] [ASkyBlock] BETA Build detected, use with precautions.
> 01:44:33 [INFO] [ASkyBlock] ASkyBlock has successfully enabled!
> 01:44:33 [INFO] Enabling Multipass v1.1.2
> 01:44:33 [INFO] [Multipass] Data provider: YAML
> 01:44:33 [INFO] Enabling MultiChat v1.0.2
> 01:44:33 [INFO] Enabling AutoInventory v1.0.2
> 01:44:33 [INFO] [AutoInventory] AutoInventory has been enabled!
> 01:44:33 [INFO] Starting GS4 status listener
> 01:44:33 [INFO] Setting query port to 30120
> 01:44:33 [INFO] Query is running on 0.0.0.0:30120
> 01:44:33 [INFO] Default game type: Survival Mode
> 01:44:33 [INFO] Done (21.496s)! For help, type "help" or "?"
> 01:44:33 [INFO] (CONSOLE): Lag Cleared!
> 01:45:10 [INFO] Trxgically[/73.79.235.126:4575] logged in with entity id 1 at (SkyBlockSpawn, -0.7914, 64.0, 9.9561)
> 01:45:12 [INFO] Trxgically joined the game
[Pterodactyl Daemon] Server marked as STOPPING
> stop
01:48:20 [INFO] [CONSOLE: Stopping the server]
> 01:48:20 [INFO] Disabling AutoInventory v1.0.2
> 01:48:20 [INFO] [AutoInventory] AutoInventory has been disabled!
> 01:48:20 [INFO] Disabling MultiChat v1.0.2
> 01:48:20 [INFO] Disabling Multipass v1.1.2
> 01:48:20 [INFO] Disabling ASkyBlock v0.4.8-ALPHA
> 01:48:20 [INFO] [ASkyBlock] Saving islands framework
> 01:48:20 [INFO] [ASkyBlock] Saving worlds...
> 01:48:20 [INFO] [ASkyBlock] Closing databases...
> 01:48:20 [INFO] [ASkyBlock] Saving offline messages...
> 01:48:20 [INFO] [ASkyBlock] ASkyBlock has successfully disabled. Goodbye
> 01:48:20 [INFO] Disabling AutoSpawn v1.0
> 01:48:20 [INFO] Disabling EssentialsNK v1.5.0
> 01:48:20 [INFO] Disabling AutoLagClear v1
> 01:48:20 [INFO] [AutoLagClear] AutoLagClear - [Disabled]
> 01:48:20 [INFO] Disabling SimpleScoreboards v2.2
> 01:48:20 [INFO] Disabling AdvancedWelcome v1.1
> 01:48:20 [INFO] Disabling MobPlugin v1.5.9
> 01:48:20 [INFO] Disabling RollBossBar v1.1.0
> 01:48:20 [INFO] Disabling WorldEssentials v2.0.3
> 01:48:20 [INFO] Disabling EconomyAPI v1.0.1
> 01:48:20 [INFO] Disabling DbLib v0.2.5
> 01:48:20 [INFO] Trxgically left the game
> 01:48:20 [INFO] Trxgically[/73.79.235.126:4575] logged out due to Server closed
> 01:48:20 [INFO] Unloading level "SkyBlockSpawn"
> 01:48:21 [INFO] Unloading level "nether"
> 01:48:21 [INFO] Unloading level "SkyBlock"
> ]0;Stopping Server...01:48:21 [INFO] Stopping other threads
>
Took too long to stop, server was killed forcefully!
[Pterodactyl Daemon] Server marked as OFF
[Pterodactyl Daemon] Server marked as STARTING
[Pterodactyl Daemon] Checking size of server data directory...
[Pterodactyl Daemon] Disk Usage: 57M / 10000M
[Pterodactyl Daemon] Ensuring file permissions.
[Pterodactyl Daemon] Running server preflight.
[Pterodactyl Daemon] Starting server container.
java version "1.8.0_192"
Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.192-b12, mixed mode)
:/home/container$ java -Xms128M -Xmx4000M -jar nukkit.jar
Using log level 'INFO'
]0;Starting Nukkit Server For Minecraft: PE> 01:48:32 [INFO] Loading nukkit.yml...
> 01:48:33 [INFO] Loading server properties...
> 01:48:33 [INFO] Selected English (eng) as the base language
> 01:48:33 [INFO] Starting Minecraft: PE server version v1.8.0
> 01:48:33 [INFO] Selected Zlib Provider: 2 (cn.nukkit.utils.ZlibThreadLocal)
> 01:48:33 [INFO] Opening server on 0.0.0.0:30120
> 01:48:33 [INFO] This server is running Nukkit version git-a694cf7 "" (API 1.0.7)
> 01:48:33 [INFO] Nukkit is distributed under the LGPL License
> 01:48:37 [INFO] Loading recipes...
> 01:48:38 [INFO] Loaded 954 recipes.
> 01:48:38 [INFO] Successfully loaded 0 resource packs
> 01:48:38 [INFO] Loading DbLib v0.2.5
> 01:48:39 [INFO] [DbLib] Establishing a connection withjdbc:sqlite:nukkit.db (user:nLuokakdiitn)g [cmlass `com.mysql.[jmdbc.Driver'. Thi
s is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered > via the SPI and manual loading of the driver class is generally unnecessary.
01:48:39 [INFO] Epoll is available. EpollEventLoop will be used.
> 01:48:39 [INFO] [DbLib] DbLib 0.2.5 created by fromgate for nukkit.ru
> 01:48:39 [INFO] Loading PlaceholderAPI v1.2
> 01:48:39 [INFO] [PlaceholderAPI] Downloading KotlinLib...
> 01:48:43 [INFO] [PlaceholderAPI] KotlinLib successfully downloaded
> 01:48:43 [INFO] Loading KotlinLib v1.0
> 01:48:44 [INFO] Loading EconomyAPI v1.0.1
> 01:48:44 [INFO] Loading WorldEssentials v2.0.3
> 01:48:44 [INFO] Loading KotlinLib v1.0
> 01:48:44 [INFO] Loading RollBossBar v1.1.0
> 01:48:44 [INFO] Loading SimpleCrates v0.9.8
> 01:48:44 [INFO] [SimpleCrates] Loading crates...
> 01:48:44 [INFO] Loading MobPlugin v1.5.9
> 01:48:44 [INFO] Loading AdvancedWelcome v1.1
> 01:48:44 [INFO] Loading SimpleScoreboards v2.2
> 01:48:44 [INFO] Loading SRegionProtector v15.1
> 01:48:44 [INFO] Loading AutoLagClear v1
> 01:48:44 [INFO] Loading ScoreboardPlugin v1.0
> 01:48:45 [INFO] Loading EssentialsNK v1.5.0
> 01:48:45 [INFO] Loading AutoSpawn v1.0
> 01:48:45 [INFO] Loading ASkyBlock v0.4.8-ALPHA
> 01:48:45 [INFO] ASkyBlock build-number: a694cf7
> 01:48:45 [INFO] ASkyBlock commit-number: a694cf7b0fe6dcfa3a9dd08801bccd76b83e3316
> 01:48:45 [INFO] [ASkyBlock] Successfully checked config.yml
> 01:48:45 [INFO] Loading Multipass v1.1.2
> 01:48:45 [INFO] Loading MultiChat v1.0.2
> 01:48:45 [INFO] Loading AutoInventory v1.0.2
> 01:48:45 [INFO] [AutoInventory] AutoInventory has been loaded!
> 01:48:45 [INFO] Enabling MobPlugin v1.5.9
> 01:48:46 [INFO] Preparing level "SkyBlockSpawn"
> 01:48:46 [INFO] Preparing level "nether"
> 01:48:46 [INFO] Enabling DbLib v0.2.5
> 01:48:46 [INFO] Enabling KotlinLib v1.0
> 01:48:46 [INFO] Enabling PlaceholderAPI v1.2
> 01:48:46 [INFO] Enabling EconomyAPI v1.0.1
> 01:48:46 [NOTICE] [EconomyAPI] Data provider was set to: Yaml
> 01:48:46 [INFO] Enabling WorldEssentials v2.0.3
> 01:48:46 [INFO] Enabling RollBossBar v1.1.0
> 01:48:46 [INFO] Enabling SimpleCrates v0.9.8
> 01:48:47 [INFO] SimpleCrates is up to date, with configuration version 0.9.8!
> Unknown
Unknown
01:48:47 [INFO] [SimpleCrates] Crates loaded!
> 01:48:47 [INFO] [SimpleCrates] Plugin enabled!
> 01:48:47 [INFO] Enabling AdvancedWelcome v1.1
> 01:48:47 [INFO] [AdvancedWelcome] WelcomeUI By SIVANNKH has been enabled!
> 01:48:47 [INFO] Enabling SimpleScoreboards v2.2
> 01:48:47 [INFO] Enabling SRegionProtector v15.1
> 01:48:47 [INFO] [SRegionProtector] Initializing SRegionProtector V_15.1 by Sergey Dertan...
> 01:48:47 [INFO] [SRegionProtector] Settings initializing...
> 01:48:47 [INFO] [SRegionProtector] Data provider initializing...
> 01:48:47 [INFO] [SRegionProtector] Data provider was set to YAML
> 01:48:47 [INFO] [SRegionProtector] Regions initializing...
> 01:48:47 [INFO] [SRegionProtector] Loaded 0 regions.
> 01:48:47 [INFO] [SRegionProtector] Chunks initializing...
> 01:48:47 [INFO] [SRegionProtector] Loaded 0 chunks.
> 01:48:47 [INFO] [SRegionProtector] Events handlers initializing...
> 01:48:47 [ALERT] java.lang.RuntimeException: java.lang.NoClassDefFoundError: cn/nukkit/event/block/LiquidFlowEvent
at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:439)
at cn.nukkit.Server.enablePlugin(Server.java:676)
at cn.nukkit.Server.enablePlugins(Server.java:665)
at cn.nukkit.Server.<init>(Server.java:507)
at cn.nukkit.Nukkit.main(Nukkit.java:109)
Caused by: java.lang.NoClassDefFoundError: cn/nukkit/event/block/LiquidFlowEvent
at Sergey_Dertan.SRegionProtector.Main.SRegionProtectorMain.initEventsHandlers(SRegionProtectorMain.java:200)
at Sergey_Dertan.SRegionProtector.Main.SRegionProtectorMain.onEnable(SRegionProtectorMain.java:84)
at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89)
at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117)
at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:435)
... 4 more
Caused by: java.lang.ClassNotFoundException: cn.nukkit.event.block.LiquidFlowEvent
at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:34)
at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:28)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 9 more
> 01:48:47 [INFO] Disabling SRegionProtector v15.1
> 01:48:47 [INFO] [SRegionProtector] Disabling SRegionProtector V_15.1 by Sergey Dertan...

**Comment by SergeyDertan** [comment]
U need to update nukkit
https://github.com/NukkitX/Nukkit/commit/d996392125953ff33cb5c97091345d12238ce243
