### ISSUE TITLE
Is there any development 

### ISSUE THREAD

**Issue by Djwhitelion** [SergeyDertan/SRegionProtector#76]
Hi. Is there any development going on, on this plugin/addon for bedrock? If not. Do you/anyone know of an plugin/addon that you can do the same thing with? Trying to protect things I make on a server I own that my kids play on as well. I'm really enjoying making things for them. But I would love a way to protect stuff I make from accidentally being broken because my kids and nephew's are young.

**Comment by SergeyDertan** [comment]
Hi
Currently there is no development, not much activity to do so.
You can try some forks, they may work
Like [this](https://github.com/edshPC/PNXRegionProtector)
